# Generated by Django 3.2.4 on 2021-06-22 09:58

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Blog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=100, null=True)),
                ('blog', models.TextField()),
                ('pic', models.ImageField(upload_to=None)),
                ('bdate', models.DateTimeField(auto_now=True)),
            ],
        ),
    ]
